:: This file was generated by Advanced Installer version 18.3.
:: The licensed user that generated this file has complete rights of ownership over it.

:: The file can be customized as per the user's requirements, for automating his repackaging processes.
:: More details on how to customize this file:
:: https://www.advancedinstaller.com/user-guide/repackager-cli.html

:: Read more about Advanced Installer:
:: https://www.advancedinstaller.com/ 

:: Read more about the Repackager tool from Advanced Installer:
:: https://www.advancedinstaller.com/repackager.html 

"C:\Program Files (x86)\Caphyon\Advanced Installer 18.3\bin\x64\RepackagerCLI.exe" /ProductLanguage "1033" /SetupPath "C:\Users\WDAGUtilityAccount\Downloads\AutoHotkey_1.1.33.09_setup.exe" /ProccesMonitor /ProductName "AutoHotkey" /ProductCompany "Your Company" /CheckMachineState /PromptAfterInstall /Configuration "Default" /OutputPath "C:\Users\WDAGUtilityAccount\Downloads\AutoHotkey-Files" /ProductVersion "1.1.33.9" 
pause